#!/bin/sh

CFG=cfg

if [ -f "$CFG" -a ! -w "$CFG" ]
then
    echo "Not writing over write-protected cfg script"
    exit 2
fi

if [ -f "$CFG" ]
then
    rm "$CFG"
fi

touch "$CFG"
if [ "x$DEBUG" != "x" ]
then
    echo "export DEBUG='$DEBUG'" >> "$CFG"
fi
if [ "x$CC" != "x" ]
then
    echo "export CC='$CC'" >> $CFG
fi
if [ "x$CXX" != "x" ]
then
    echo "export CXX='$CXX'" >> $CFG
fi
CONFIGURE=`echo $0 | sed 's/cfg/configure/' `
echo "$CONFIGURE $*" >> $CFG
chmod u+x $CFG
sh -x $CFG
